-- Create table for note entity
create table note
(
    id         bigint generated by default as identity
        constraint note_pkey
            primary key,
    datecreate timestamp,
    text       varchar(255),
    topic      varchar(255)
);
-- Create table for hashtag entity
create table hashtag
(
    id    bigint generated by default as identity
        constraint hashtag_pkey
            primary key,
    title varchar(255)
);
-- Create table describe relation between not and hashtag entity
create table note_hashtag
(
    note_id    bigint not null,
    constraint fk_note_id
        foreign key (note_id)
            references note (id),
    hashtag_id bigint not null,
    constraint fk_hashtag_id
        foreign key (hashtag_id)
            references hashtag (id)
);
